version: 2.1

jobs:
  lint-code:
    docker:
      - image: python:3.7-alpine3.11
    steps:
      - checkout
      - run:
          name: Install python dependencies
          command: |
            apk add curl
            apk add --no-cache build-base
            make install
      - run:
          name: Install Hadolint
          command: |
            curl -sL -o /usr/local/bin/hadolint "https://github.com/hadolint/hadolint/releases/download/v1.18.0/hadolint-$(uname -s)-$(uname -m)"
            chmod +x /usr/local/bin/hadolint   
      - run:
          name: Run Lint Checks
          command: make lint             

workflows:
  default:
    jobs: 
      - lint-code