build-frontend:
  docker:
    - image: python:3.7-alpine3.11
  steps:
    - checkout
    - run:
        name: Test
        command: echo "Test"

workflows:
  default:
    jobs: 
      - build-frontend