version: 2.1

jobs:
  lint-code:
    docker:
      - image: python:3.7-alpine3.11
    steps:
      - checkout
      - run:
          name: install python dependencies
          command: |
            sudo apt-get install build-essential 
            pip install pylint===2.4.4 
            
      # - run:
      #     name: Install Hadolint
      #     command: |
      #       curl -sL -o /usr/local/bin/hadolint "https://github.com/hadolint/hadolint/releases/download/v1.18.0/hadolint-$(uname -s)-$(uname -m)"
      #       chmod +x /usr/local/bin/hadolint   
      # Run lint checks
      - run:
          name: Run Lint Checks
          command: make lint             

workflows:
  default:
    jobs: 
      - lint-code